<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.hzj.redis</groupId>
  <artifactId>redis-spring-boot-starter</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <name>redis-spring-boot-starter</name>
  <url>http://maven.apache.org</url>
  <description>Redis Spring Boot Starter</description>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <gson.version>2.14.0</gson.version>
    <okhttp.version>4.12.0</okhttp.version>
    <spring.boot.starter.version>3.2.4</spring.boot.starter.version>
    <junit.version>3.8.1</junit.version>
    <redisson.version>3.34.0</redisson.version>
    <commons-pool2.version>2.12.1</commons-pool2.version>
  </properties>

  <dependencies>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <version>${spring.boot.starter.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
      <version>${spring.boot.starter.version}</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
      <version>${commons-pool2.version}</version>
    </dependency>

    <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson</artifactId>
      <version>${redisson.version}</version>
    </dependency>


    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>${spring.boot.starter.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.hzj.common</groupId>
      <artifactId>hzj-common</artifactId>
      <version>1.0.0</version>
    </dependency>

  </dependencies>


  <distributionManagement>
    <repository>
      <id>local-repo</id>
      <url>file://${project.basedir}/maven-repository</url>
    </repository>
  </distributionManagement>
</project>
